#  Common Docker configuration file.
#  Never use directly.
#  Use with development.yml, staging.yml, or production.yml instead.

version: '3.6'
volumes:
  postgres-data:
    name: postgres-data

services:
# Django database and http server
  database:
    container_name: homesite_db
    image: postgres
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "10"
  web:
    container_name: homesite_web
    command: bash ./docker/backend/start.sh
    build: ./docker/backend/
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/bin/sh /code/docker/backend/healthcheck.sh"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s
    volumes:
      - .:/code
      - ./docker/backend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - database
    logging:
      driver: "json-file"
      options:
        max-size: "500k"
        max-file: "10"
